# Generated by Django 4.1 on 2022-08-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioApp', '0002_inventario_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
